#!/bin/bash
echo "synccode started: $(date)"
rsync -avz  -e "ssh " --exclude="venv/*" --exclude="static/*" --exclude="dist/*" --exclude=".git/*" --exclude="node_modules/*" . whyis:/apps/nanomine/
rsync -avz  -e "ssh " --exclude="venv/*" --exclude="static/*" --exclude="dist/*" --exclude=".git/*" --exclude="node_modules/*" ../mm-model-viewers/ whyis:/apps/mm-model-viewers/
ssh whyis "cd mm-model-viewers; npm run build:release"
ssh whyis "cd nanomine;npm run build"
ssh whyisroot "systemctl stop apache2"
ssh whyisroot "systemctl stop nm-rest"
ssh whyis "rm nanomine/rest/nanomine.log"
ssh whyisroot "systemctl start nm-rest"
ssh whyisroot "systemctl start apache2"
echo "synccode ended: $(date)"

