#!/bin/bash
nobld=${1-:''}
echo "synccode started: $(date)"
rsync -avz  -e "ssh " --exclude="venv/*" --exclude="static/*" --exclude="dist/*" --exclude=".git/*" --exclude="node_modules/*" . whyis:/apps/nanomine/
echo "For testing package.json changes, uncomment the line that re-creates all node_modules."
#ssh whyis "cd nanomine;rm -rf node_modules; npm i"

if [[ $nobld == "nobld" ]] ; then
  echo NOT running build of vue app
else
  echo Running build of vue app
  ssh whyis "cd nanomine;npm run build"
  echo completed build of vue app
fi

echo STOPPING apache2 and nm-rest
ssh whyisroot "systemctl stop apache2"
ssh whyisroot "systemctl stop nm-rest"

echo Cleaning server log
ssh whyis "rm nanomine/rest/nanomine.log"

echo Starting nm-rest and apache2
ssh whyisroot "systemctl start nm-rest"
ssh whyisroot "systemctl start apache2"

echo "synccode ended: $(date)"
