<!--
################################################################################
#
# File Name: SDFReconstruct.vue
# Application: templates
# Description:
#
# Created by: Akshay Iyer, August 18, 2018
# Customized for NanoMine
#
################################################################################
-->

<template>
  <div class="SDFReconstruct">
    <h1>{{ msg }}</h1>
    <v-container>
      <v-flex xs12>
          <h3>Description</h3>
          <br>
           <p>Upload a image / ZIP file containing set of images (Supported file formats: .jpg, .tif, .png) and click "Reconstruct".
           Reconstructions are generated by level-cutting a Gaussian Random Field (see references)</p>
           <p><strong>The SDF is a function of <italic> spatial </italic> frequency and has the unit 1/pixel.</strong></p>

            <h4> Input Options:</h4>
            <p><strong> NOTE: Images must be binarized.</strong></p>
                  <p><strong> 1) Single image:</strong> (Download <a href='http://129.105.90.149/nm/Two_pt_MCR/Input Samples/Option1.zip'>Sample</a>).
                  Supported image formats are .jpg, .tif and .png. The reconstruction results will include the input and reconstructed images in JPG format, the 2D SDF
                  (data in Input_SDF_2D.csv, plotted in SDF_2D.jpg) and it's radial average (Input_SDF_1D.csv).
                  The reconstructed images will be provided in JPEG format along with a plot comparing their autocorrelation function with the autocorrelation of input image.</p>
                  <p><strong> 2) Single image in .mat format :</strong> The .mat file must contain ONLY ONE variable named "Input" - which contains pixel values(only 0 or 1)
                  (Download <a href='http://129.105.90.149/nm/Two_pt_MCR/Input Samples/Option2.zip'>Sample</a>) The reconstruction results will include the input and reconstructed images
                   in JPG format, the 2D SDF (data in Input_SDF_2D.csv, plotted in SDF_2D.jpg) and it's radial average (Input_SDF_1D.csv).
                   The reconstructed images will be provided in JPEG format along with a plot comparing their autocorrelation function with the mean autocorrelation of input images.</p>
                   <p><strong> 3) Multiple images in ZIP File:</strong> Submit a ZIP file containing multiple images of same size (in pixels).
                    DO NOT ZIP the folder containing images; select all images and ZIP them directly. (Download <a href='http://129.105.90.149/nm/Two_pt_MCR/Input Samples/Option3.zip'>Sample</a>). The mean SDF (averaged over all input images) will be used for reconstruction.
                    The results include 2D and 1D SDF for all input		images provided in folders named "Input1", "Input2" etc. (one for each input image).
                    The mean SDF of input images are provided in CSV files "SDF_1D_mean.csv" and "SDF_2D_mean.csv" and the 2D mean plotted in "SDF_2D.jpg".
                    The reconstructed images will be provided in JPEG format along with a plot comparing their autocorrelation function with the mean autocorrelation of input images.</p>
      </v-flex>
          <h2> Create Agent to accept user uploaded files and process it in MATLAB</h2>

    </v-container>

    <h4>Reference</h4>
    <v-flex xs12>
        <p>Yu, S., Zhang, Y., Wang, C., Lee, W.K., Dong, B., Odom, T.W., Sun, C. and Chen, W., 2017. Characterization and design of functional quasi-random nanostructured materials using spectral density function. Journal of Mechanical Design, 139(7), p.071401.</p>
        <p>Lee, W. K., Yu, S., Engel, C. J., Reese, T., Rhee, D., Chen, W., & Odom, T. W. (2017). Concurrent design of quasi-random photonic nanostructures. Proceedings of the National Academy of Sciences, 114(33), 8734-8739.</p>

    </v-flex>
  </div>
</template>

<script>
export default {
  name: 'SDFReconstruct',
  data () {
    return {
      msg: 'Microstructure Reconstruction - Spectral Density Function'
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
  img {
    width: 240px;
  }
  h4 {
    text-transform: uppercase;
  }
</style>
