#!/usr/bin/env bash
# ChemProps caretaker executes hourly, but only updates ChemProps based on configuration
# This approach allows flexibilty on when ChemProps is updated
runHr=23 # 11 PM
runDay=0 #Sunday

curHr="$(date +%k)"
curDay="$(date +%u)"

if (( ${curDay} == ${runDay} && ${curHr} == ${runHr} )); then
  echo "Executing ChemProps Caretaker $(date)"
  (su - whyis -c "/apps/nanomine/src/scripts/run_chemprops_updater")
  echo "Done executing ChemProps Caretaker $(date)"
fi

